# Generated by Django 2.2.7 on 2019-11-13 18:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ucusers', '0007_person_personalitytraits'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfDeparture', models.DateTimeField(blank=True, null=True)),
                ('timeOfArrival', models.DateTimeField(blank=True, null=True)),
                ('origin', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('isDriver', models.BooleanField(blank=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ucusers.Person')),
            ],
            options={
                'verbose_name_plural': 'Person Itineraries',
            },
        ),
    ]
