# Generated by Django 2.2.4 on 2019-09-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smovusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartmovingprofile',
            name='type_movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smovusers.MovementType'),
        ),
    ]
