# Generated by Django 2.2.4 on 2020-01-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smnavigation', '0004_auto_20200109_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrequest',
            name='report_light',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navigationrequest',
            name='report_severe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
