# Generated by Django 2.2.4 on 2020-01-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smnavigation', '0005_auto_20200109_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrequest',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
