# Generated by Django 2.2.5 on 2019-09-10 19:53

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "application",
                    models.URLField(db_index=True, help_text="The application that is sourcing the event."),
                ),
                ("e_type", models.URLField(db_index=True, help_text="The type of event.")),
                ("agent", models.URLField(db_index=True, help_text="Who is the main agent in the event.")),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        db_index=True, help_text="Sensor position at the instant the event takes place.", srid=4326
                    ),
                ),
                (
                    "instant",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Point in time when the event occurs.",
                    ),
                ),
                ("extra_information", django.contrib.postgres.fields.jsonb.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
