# Generated by Django 2.2.5 on 2019-09-10 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("smevents", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="application",
            field=models.ForeignKey(
                help_text="The application that is sourcing the event.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="smasu.Application",
            ),
        )
    ]
