# Generated by Django 2.2.5 on 2019-09-10 22:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("smevents", "0002_auto_20190910_2100")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="agent",
            field=models.URLField(blank=True, db_index=True, help_text="Who is the main agent in the event."),
        ),
        migrations.AlterField(
            model_name="event",
            name="position",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, db_index=True, help_text="Sensor position at the instant the event takes place.", srid=4326
            ),
        ),
    ]
