# Generated by Django 2.2.4 on 2019-08-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spusers', '0003_smartparkingprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartparkingprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='smartparkingprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=16),
            preserve_default=False,
        ),
    ]
