# Generated by Django 2.2.4 on 2019-08-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spusers', '0004_auto_20190824_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartparkingprofile',
            name='alias',
        ),
    ]
