# Generated by Django 2.2.5 on 2019-11-29 13:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ucusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfDeparture', models.DateTimeField(blank=True, null=True)),
                ('timeOfArrival', models.DateTimeField(blank=True, null=True)),
                ('origin', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('isDriver', models.BooleanField(blank=True, null=True)),
                ('ucarpoolingProfile', models.ForeignKey
                    (
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='ucusers.UcarpoolingProfile'
                    )
                 ),
            ],
            options={
                'verbose_name_plural': 'User Itineraries',
            },
        ),
    ]
