# Generated by Django 2.2.5 on 2019-11-30 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccarpool', '0003_auto_20191130_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpoolitinerary',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='carpoolitinerary',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='carpoolitinerary',
            name='timeOfArrival',
        ),
        migrations.RemoveField(
            model_name='carpoolitinerary',
            name='timeOfDeparture',
        ),
        migrations.AddField(
            model_name='carpoolitinerary',
            name='itinerary',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uccarpool.UserItinerary'),
        ),
    ]
