# Generated by Django 2.2.5 on 2019-12-06 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucusers', '0001_initial'),
        ('uccarpool', '0004_auto_20191130_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCarpool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='recipient',
                    to='ucusers.UcarpoolingProfile')),
                ('sender', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sender',
                    to='ucusers.UcarpoolingProfile')),
                ('subject', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='uccarpool.Carpool')),
            ],
        ),
    ]
