# Generated by Django 2.2.5 on 2019-12-16 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucusers', '0001_initial'),
        ('uccarpool', '0005_requestcarpool'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarpoolItinerary',
            new_name='Route',
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name_plural': 'Routes'},
        ),
        migrations.RenameField(
            model_name='carpool',
            old_name='carpoolItinerary',
            new_name='route',
        ),
        migrations.CreateModel(
            name='PersonalityMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalityMatchPercentage', models.FloatField()),
                ('user1', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='user1',
                    to='ucusers.UcarpoolingProfile')),
                ('user2', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='user2',
                    to='ucusers.UcarpoolingProfile')),
            ],
        ),
    ]
