# Generated by Django 2.2.5 on 2019-12-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uccarpool', '0007_auto_20191218_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalityMatch',
        ),
    ]
