# Generated by Django 2.2.5 on 2019-12-24 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccarpool', '0008_delete_personalitymatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryroute',
            name='agg_cost',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
