# Generated by Django 2.2.5 on 2019-12-24 19:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccarpool', '0010_auto_20191224_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryroute',
            name='aggCost',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
