# Generated by Django 2.2.5 on 2020-01-02 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccarpool', '0011_auto_20191224_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpool',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='uccarpool.UserItinerary'),
        ),
    ]
