# Generated by Django 2.2.9 on 2020-01-13 18:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccarpool', '0012_auto_20200102_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryroute',
            name='path',
        ),
        migrations.AddField(
            model_name='itineraryroute',
            name='pathLatitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True),
                                                            blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='itineraryroute',
            name='pathLongitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True),
                                                            blank=True, default=list, null=True, size=None),
        ),
    ]
