# Generated by Django 2.2.9 on 2020-04-12 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucusers', '0003_auto_20191223_2001'),
        ('uccarpool', '0013_auto_20200113_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpoolRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='qualified', to='ucusers.UcarpoolingProfile')),
                ('qualifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='qualifier', to='ucusers.UcarpoolingProfile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='uccarpool.Carpool')),
            ],
        ),
    ]
