# Generated by Django 2.2.4 on 2019-10-25 03:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smreports', '0003_auto_20191024_2345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('reportpoi', 'user', 'value')},
        ),
    ]
