# Generated by Django 2.2.4 on 2019-10-25 23:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smreports', '0004_auto_20191025_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
