# Generated by Django 2.2.4 on 2019-11-19 14:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smreports', '0005_contribution_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, srid=4326)),
                ('status',
                    models.CharField(
                        choices=[
                            ('U', 'Unknown'),
                            ('C', 'Confirmed'),
                            ('R', 'Resolved')], default='U', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('report_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='smreports.ReportType')),
                ('user_created',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Contribution',
            new_name='StatusUpdate',
        ),
        migrations.DeleteModel(
            name='ReportPoi',
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='reportid',
            field=models.ForeignKey(default='U', on_delete=django.db.models.deletion.CASCADE, to='smreports.Report'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='statusupdate',
            unique_together={('reportid', 'user', 'value')},
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='reportpoi',
        ),
    ]
