# Generated by Django 2.2.4 on 2019-11-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smreports', '0005_contribution_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpoi',
            name='status',
            field=models.CharField(choices=[
                ('U', 'Unknown'), ('C', 'Confirmed'), ('R', 'Resolved')], default='U', max_length=15),
        ),
    ]
