# Generated by Django 2.2.4 on 2019-12-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smreports', '0006_auto_20191119_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='gid',
            field=models.BigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
