# Generated by Django 2.2.4 on 2019-09-01 19:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("radio", models.FloatField()),
                ("name", models.CharField(max_length=50)),
                ("center", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        choices=[("F", "Free"), ("O", "Occupied"), ("U", "Unknown")], default="U", max_length=15
                    ),
                ),
                ("polygon", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "parking_lot",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="splots.ParkingLot"),
                ),
            ],
        ),
    ]
