# Generated by Django 2.2.4 on 2019-09-05 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("splots", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="parkingspot", name="parking_lot"),
        migrations.AddField(
            model_name="parkingspot",
            name="lot",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="spots", to="splots.ParkingLot"
            ),
            preserve_default=False,
        ),
    ]
