# Generated by Django 2.2.5 on 2019-09-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splots', '0002_auto_20190905_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='radio',
            new_name='monitoring_distance',
        ),
    ]
