# Generated by Django 2.2.5 on 2019-11-28 12:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UcarpoolingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=16)),
                ('smoker', models.BooleanField()),
                ('musicTaste',
                    django.contrib.postgres.fields.ArrayField
                    (base_field=models.CharField
                        (choices=[
                            ('NO_PREF', 'No preference'),
                            ('SILENCE', 'I like silence'),
                            ('POP', 'Pop'),
                            ('TECHNO', 'Techno'),
                            ('ELECTRONIC', 'Electronic'),
                            ('ROCK', 'Rock'), ('METAL', 'Metal'),
                            ('RAP', 'Rap'),
                            ('REGGAE', 'Reggae'),
                            ('CUMBIA', 'Cumbia'),
                            ('REGGAETON', 'Reggaeton'),
                            ('TRAP', 'Trap'),
                            ('FUNK', 'Funk')], max_length=15), default=list, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
