# Generated by Django 2.2.5 on 2019-12-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucarpoolingprofile',
            name='eloquence_level',
            field=models.IntegerField(
                blank=True, choices=[(1, 'Introverted'), (2, 'Medium'), (3, 'Extroverted')], null=True),
        ),
    ]
