# Generated by Django 2.2.5 on 2019-11-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucusers', '0002_auto_20191111_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UcarpoolingPersonalityTraitType',
            new_name='PersonalityTraitType',
        ),
    ]
