# Generated by Django 2.2.5 on 2019-12-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucusers', '0002_ucarpoolingprofile_eloquence_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucarpoolingprofile',
            old_name='eloquence_level',
            new_name='eloquenceLevel',
        ),
    ]
