# Generated by Django 2.2.5 on 2019-11-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucusers', '0003_auto_20191111_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalityTraitValue', models.CharField(max_length=64)),
                ('personalityTraitType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucusers.PersonalityTraitType')),
            ],
        ),
    ]
