# Generated by Django 2.2.5 on 2019-11-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucusers', '0004_personalitytrait'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='personalitytrait',
            constraint=models.UniqueConstraint(fields=('personalityTraitType', 'personalityTraitValue'), name='unique_value'),
        ),
    ]
