# Generated by Django 2.2.5 on 2019-11-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucusers', '0005_auto_20191111_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personId', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='personalitytrait',
            name='unique_value',
        ),
        migrations.AddConstraint(
            model_name='personalitytrait',
            constraint=models.UniqueConstraint(fields=('personalityTraitType', 'personalityTraitValue'), name='unique_personality_and_value'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('personId',), name='unique_person_id'),
        ),
    ]
