# Generated by Django 2.2.5 on 2019-11-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucusers', '0006_auto_20191111_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='personalityTraits',
            field=models.ManyToManyField(to='ucusers.PersonalityTrait'),
        ),
    ]
