# Generated by Django 2.2.3 on 2019-07-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smusers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
